version: '3.8'

services:
  friend-recommender-api:
    container_name: friends-recommender-api
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/app/entrypoint.sh"]
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
